language: php
php:
- '5.4'
addons:
  chrome: stable
  apt:
    packages:
    - fonts-noto-hinted
cache:
  directories:
  - vendor

before_script:
- composer install
- nvm install 7
- npm install
- npm run install-wp
script:
- npm run test
